spring:
  application:
    name: walletriskscorer
  datasource:
    url: jdbc:postgresql://localhost:5433/walletcache
    username: sedisamuel
    password: sam182006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

gemini:
  api:
    key: ${GEMINI_API_KEY}

moralis:
  api:
    key: ${MORALIS_API_KEY}