spring:
  application:
    name: walletriskscorer
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/walletcache}
    username: ${DB_USERNAME:sedisamuel}
    password: ${DB_PASSWORD:sam182006}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8084}

gemini:
  api:
    key: ${GEMINI_API_KEY}

moralis:
  api:
    key: ${MORALIS_API_KEY}